services:

  openvpn-as:
    image: docker.io/wachira90/openvpn-as:v1
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    ports:
      - "943:943"
      - "443:443"
      - "1194:1194/udp"
    volumes:
      - /mnt/vpn/:/openvpn
